import streamlit as st

st.set_page_config(
    page_title="NeuroVision AI",
    layout="wide"
)

# -----------------------------
# Custom CSS
# -----------------------------

st.markdown("""
<style>

.main {
    padding-top: 2rem;
}

div.stButton > button {
    width: 100%;
    height: 75px;
    font-size: 24px;
    font-weight: bold;
    border-radius: 15px;
}

.big-title {
    text-align: center;
    font-size: 50px;
    font-weight: bold;
}

.sub-title {
    text-align: center;
    font-size: 22px;
    color: #B0B0B0;
}

</style>
""", unsafe_allow_html=True)

# -----------------------------
# Header
# -----------------------------

st.markdown(
    '<p class="big-title">NeuroVision AI</p>',
    unsafe_allow_html=True
)

st.markdown(
    '<p class="sub-title">AI-Based Brain Disease Detection System</p>',
    unsafe_allow_html=True
)

st.markdown("---")

# -----------------------------
# Project Overview
# -----------------------------

st.header("Project Overview")

st.write("""
NeuroVision AI is an academic project developed
for MRI-based Brain Tumor and Alzheimer's Disease
analysis using Deep Learning.

The system uses ResNet18 and Grad-CAM to
perform image classification and provide
visual explanations of predictions.
""")

st.markdown("---")

# -----------------------------
# Features
# -----------------------------

st.header("Key Features")

st.write("""
• Brain Tumor Detection

• Alzheimer's Disease Detection

• Confidence Score Generation

• MRI Heatmap Visualization

• Explainable AI using Grad-CAM
""")

st.markdown("---")

# -----------------------------
# Technologies
# -----------------------------

st.header("Technologies Used")

st.write("""
• PyTorch

• ResNet18

• Streamlit

• Grad-CAM

• MRI Datasets from Kaggle
""")

st.markdown("---")

# -----------------------------
# Dataset Information
# -----------------------------

st.header("Dataset Information")

st.write("""
The MRI datasets used in this project were
obtained from publicly available Kaggle datasets
and are used strictly for academic and
research purposes.
""")

st.markdown("---")

# -----------------------------
# Disclaimer
# -----------------------------

st.header("Medical Disclaimer")

st.warning("""
This application is an academic project developed
for educational and research purposes only.

The predictions generated by this system should
not be considered a medical diagnosis.

Please consult qualified healthcare professionals
before making medical decisions.

The developers are not responsible for medical
decisions taken based on the predictions generated
by this system.
""")

# -----------------------------
# Consent
# -----------------------------

consent = st.checkbox(
    "I understand that this application is an academic project and is not a substitute for professional medical advice."
)

st.markdown("")

if consent:

    st.success(
        "Consent accepted. Click the button below to continue."
    )

    if st.button(
        "USE THE MODEL",
        type="primary",
        use_container_width=True
    ):
        st.switch_page(
            "pages/1_Model_Selection.py"
        )

else:

    st.info(
        "Please accept the disclaimer before proceeding."
    )