from pathlib import Path

import streamlit as st

import torch
import torch.nn as nn

from torchvision import models, transforms
from PIL import Image

import numpy as np

from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image

# -----------------------------------
# PAGE CONFIG
# -----------------------------------

st.set_page_config(
    page_title="Brain Tumor Detection",
    layout="wide"
)

# -----------------------------------
# PATHS
# -----------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

model_path = (
    BASE_DIR
    / "brain_tumor"
    / "models"
    / "tumor_model.pth"
)

# -----------------------------------
# MODEL
# -----------------------------------

classes = [
    "glioma",
    "meningioma",
    "notumor",
    "pituitary"
]

labels = {
    "glioma": "Glioma Tumor",
    "meningioma": "Meningioma Tumor",
    "pituitary": "Pituitary Tumor",
    "notumor": "No Tumor Detected"
}


@st.cache_resource
def load_model():

    model = models.resnet18(
        weights=None
    )

    model.fc = nn.Linear(
        model.fc.in_features,
        4
    )

    model.load_state_dict(
        torch.load(
            model_path,
            map_location="cpu"
        )
    )

    model.eval()

    return model


model = load_model()

# -----------------------------------
# HEADER
# -----------------------------------

st.title(
    "Brain Tumor Detection"
)

st.warning(
    """
This application is an academic project.

Predictions generated by this system should not
be considered a medical diagnosis.

Please consult qualified healthcare professionals.
"""
)

st.markdown("---")

# -----------------------------------
# INFORMATION
# -----------------------------------

with st.expander(
    "What is a Brain Tumor?",
    expanded=True
):
    st.write("""
A brain tumor is an abnormal growth of cells
inside the brain.

Tumors may be benign or malignant and can
affect normal brain function.
""")

with st.expander(
    "Causes"
):
    st.write("""
• Genetic mutations

• Radiation exposure

• Family history

• Unknown biological factors
""")

with st.expander(
    "Symptoms"
):
    st.write("""
• Persistent headaches

• Seizures

• Vision problems

• Memory issues

• Speech difficulty

• Balance problems
""")

with st.expander(
    "Tumor Types Detected"
):
    st.write("""
• Glioma

• Meningioma

• Pituitary Tumor

• No Tumor
""")

st.markdown("---")

# -----------------------------------
# CONSENT
# -----------------------------------

consent = st.checkbox(
    "I understand this is an educational project and not a medical diagnosis."
)

if not consent:

    st.info(
        "Please accept the disclaimer before uploading an MRI scan."
    )

    st.stop()

# -----------------------------------
# FILE UPLOAD
# -----------------------------------

uploaded_file = st.file_uploader(
    "Upload MRI Scan",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is None:

    st.stop()

# -----------------------------------
# IMAGE
# -----------------------------------

image = Image.open(
    uploaded_file
).convert(
    "RGB"
)

transform = transforms.Compose([
    transforms.Resize(
        (224, 224)
    ),
    transforms.ToTensor()
])

input_tensor = transform(
    image
).unsqueeze(
    0
)

# -----------------------------------
# PREDICTION
# -----------------------------------

with st.spinner(
    "Analyzing MRI..."
):

    with torch.no_grad():

        output = model(
            input_tensor
        )

        probabilities = torch.softmax(
            output,
            dim=1
        )

        prediction = torch.argmax(
            probabilities,
            dim=1
        )

        confidence = (
            probabilities[0][prediction.item()]
            * 100
        )

predicted_class = classes[
    prediction.item()
]

st.markdown("---")

st.success(
    f"Prediction: {labels[predicted_class]}"
)

st.info(
    f"Confidence: {confidence:.2f}%"
)

st.progress(
    float(confidence) / 100
)

st.markdown("---")

st.subheader(
    "Model Information"
)

st.write("""
Architecture : ResNet18

Explainability : Grad-CAM

Input Size : 224 × 224 MRI Images

Dataset : Brain Tumor MRI Dataset

Framework : PyTorch
""")
# -----------------------------------
# HEATMAP
# -----------------------------------

with st.spinner(
    "Generating Grad-CAM heatmap..."
):

    rgb_img = image.resize(
        (224, 224)
    )

    img_np = np.array(
        rgb_img
    ) / 255.0

    target_layers = [
        model.layer4[-1]
    ]

    cam = GradCAM(
        model=model,
        target_layers=target_layers
    )

    grayscale_cam = cam(
        input_tensor=input_tensor
    )[0]

    visualization = show_cam_on_image(
        img_np,
        grayscale_cam,
        use_rgb=True
    )

st.success(
    "Heatmap generated successfully."
)

# -----------------------------------
# DISPLAY
# -----------------------------------

st.markdown("---")

col1, col2 = st.columns(2)

with col1:

    st.subheader(
        "Original MRI"
    )

    st.image(
        image,
        use_container_width=True
    )

with col2:

    st.subheader(
        "Grad-CAM Heatmap"
    )

    st.image(
        visualization,
        use_container_width=True
    )

# -----------------------------------
# HEATMAP INTERPRETATION
# -----------------------------------

st.markdown("---")

st.subheader(
    "Heatmap Interpretation"
)

st.markdown("""
🔴 **Red** → Very High Attention

🟡 **Yellow** → High Attention

🟢 **Green** → Moderate Attention

🔵 **Blue** → Low Attention

The highlighted regions indicate the areas that contributed most to the AI model's prediction.
""")

# -----------------------------------
# DISCLAIMER
# -----------------------------------

st.warning(
    """
Important:

This result is generated by an AI model and
must not be considered a clinical diagnosis.

Please consult a radiologist, neurologist,
neurosurgeon, or neuro-oncologist.
"""
)

# -----------------------------------
# FOOTER
# -----------------------------------

st.markdown("---")

st.caption(
    "NeuroVision AI | Academic Project | MRI-Based Brain Disease Detection using Deep Learning and Explainable AI"
)

# -----------------------------------
# NAVIGATION
# -----------------------------------

st.markdown("---")

col1, col2 = st.columns(2)

with col1:

    if st.button(
        "Back To Model Selection",
        use_container_width=True
    ):
        st.switch_page(
            "pages/1_Model_Selection.py"
        )

with col2:

    if st.button(
        "View Project Metrics",
        use_container_width=True
    ):
        st.switch_page(
            "pages/4_Project_Metrics.py"
        )
