from pathlib import Path

import streamlit as st

import torch
import torch.nn as nn

from torchvision import models, transforms
from PIL import Image

import numpy as np

from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image

# -----------------------------------
# PAGE CONFIG
# -----------------------------------

st.set_page_config(
    page_title="Alzheimer's Disease Detection",
    layout="wide"
)

# -----------------------------------
# PATHS
# -----------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

model_path = (
    BASE_DIR
    / "Alzhimers"
    / "models"
    / "alzhimers_model.pth"
)

# -----------------------------------
# CLASSES
# -----------------------------------

classes = [
    "Mild Demented",
    "Moderate Demented",
    "Non Demented",
    "Very Mild Demented"
]

# -----------------------------------
# LOAD MODEL
# -----------------------------------

@st.cache_resource
def load_model():

    model = models.resnet18(
        weights=None
    )

    model.fc = nn.Linear(
        model.fc.in_features,
        4
    )

    model.load_state_dict(
        torch.load(
            model_path,
            map_location="cpu"
        )
    )

    model.eval()

    return model


model = load_model()

# -----------------------------------
# HEADER
# -----------------------------------

st.title(
    "Alzheimer's Disease Detection"
)

st.warning(
    """
This application is an academic project.

Predictions generated by this system should not
be considered a medical diagnosis.

Please consult qualified healthcare professionals.
"""
)

st.markdown("---")

# -----------------------------------
# INFORMATION
# -----------------------------------

with st.expander(
    "What is Alzheimer's Disease?",
    expanded=True
):
    st.write("""
Alzheimer's Disease is a progressive neurological
disorder that affects memory, thinking ability,
and behaviour.
""")

with st.expander(
    "Risk Factors"
):
    st.write("""
• Aging

• Genetics

• Family History

• Cardiovascular Disease

• Diabetes
""")

with st.expander(
    "Symptoms"
):
    st.write("""
• Memory Loss

• Confusion

• Difficulty Speaking

• Mood Changes

• Difficulty Solving Problems

• Behavioural Changes
""")

with st.expander(
    "Stages Detected"
):
    st.write("""
• Non Demented

• Very Mild Demented

• Mild Demented

• Moderate Demented
""")

st.markdown("---")

# -----------------------------------
# CONSENT
# -----------------------------------

consent = st.checkbox(
    "I understand this is an educational project and not a medical diagnosis."
)

if not consent:

    st.info(
        "Please accept the disclaimer before uploading an MRI scan."
    )

    st.stop()

# -----------------------------------
# FILE UPLOAD
# -----------------------------------

uploaded_file = st.file_uploader(
    "Upload MRI Scan",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is None:

    st.stop()

# -----------------------------------
# IMAGE
# -----------------------------------

image = Image.open(
    uploaded_file
).convert(
    "RGB"
)

transform = transforms.Compose([
    transforms.Resize(
        (224, 224)
    ),
    transforms.ToTensor()
])

input_tensor = transform(
    image
).unsqueeze(
    0
)

# -----------------------------------
# PREDICTION
# -----------------------------------

with st.spinner(
    "Analyzing MRI..."
):

    with torch.no_grad():

        output = model(
            input_tensor
        )

        probabilities = torch.softmax(
            output,
            dim=1
        )

        prediction = torch.argmax(
            probabilities,
            dim=1
        )

        confidence = (
            probabilities[0][prediction.item()]
            * 100
        )

st.markdown("---")

st.success(
    f"Prediction: {classes[prediction.item()]}"
)

st.info(
    f"Confidence: {confidence:.2f}%"
)

st.progress(
    float(confidence) / 100
)

st.markdown("---")

st.subheader(
    "Model Information"
)

st.write("""
Architecture : ResNet18

Explainability : Grad-CAM

Input Size : 224 × 224 MRI Images

Dataset : Alzheimer's MRI Dataset (4 Classes)

Framework : PyTorch
""")
# -----------------------------------
# HEATMAP
# -----------------------------------

with st.spinner(
    "Generating Grad-CAM heatmap..."
):

    rgb_img = image.resize(
        (224, 224)
    )

    img_np = np.array(
        rgb_img
    ) / 255.0

    target_layers = [
        model.layer4[-1]
    ]

    cam = GradCAM(
        model=model,
        target_layers=target_layers
    )

    grayscale_cam = cam(
        input_tensor=input_tensor
    )[0]

    visualization = show_cam_on_image(
        img_np,
        grayscale_cam,
        use_rgb=True
    )

st.success(
    "Heatmap generated successfully."
)

# -----------------------------------
# DISPLAY IMAGES
# -----------------------------------

st.markdown("---")

col1, col2 = st.columns(2)

with col1:

    st.subheader(
        "Original MRI"
    )

    st.image(
        image,
        use_container_width=True
    )

with col2:

    st.subheader(
        "Grad-CAM Heatmap"
    )

    st.image(
        visualization,
        use_container_width=True
    )

# -----------------------------------
# HEATMAP INTERPRETATION
# -----------------------------------

st.markdown("---")

st.subheader(
    "Heatmap Interpretation"
)

st.markdown("""
🔴 **Red** → Very High Attention

🟡 **Yellow** → High Attention

🟢 **Green** → Moderate Attention

🔵 **Blue** → Low Attention

The highlighted regions indicate the areas that contributed most to the AI model's prediction.
""")

# -----------------------------------
# DISCLAIMER
# -----------------------------------

st.warning(
    """
Important:

This result is generated by an AI model and
must not be considered a clinical diagnosis.

Please consult a qualified neurologist,
radiologist, or healthcare professional.
"""
)

# -----------------------------------
# FOOTER
# -----------------------------------

st.markdown("---")

st.caption(
    "NeuroVision AI | Academic Project | MRI-Based Brain Disease Detection using Deep Learning and Explainable AI"
)

# -----------------------------------
# NAVIGATION
# -----------------------------------

st.markdown("---")

col1, col2 = st.columns(2)

with col1:

    if st.button(
        "Back To Model Selection",
        use_container_width=True
    ):
        st.switch_page(
            "pages/1_Model_Selection.py"
        )

with col2:

    if st.button(
        "View Project Metrics",
        use_container_width=True
    ):
        st.switch_page(
            "pages/4_Project_Metrics.py"
        )
