import streamlit as st

from brain_tumor.evaluation import evaluate_model as evaluate_brain
from Alzhimers.evaluation import evaluate_model as evaluate_alzheimer

# -----------------------------------
# PAGE CONFIG
# -----------------------------------

st.set_page_config(
    page_title="Project Metrics",
    layout="wide"
)

# -----------------------------------
# CACHE METRICS
# -----------------------------------

@st.cache_data
def load_metrics():

    brain_metrics = evaluate_brain()

    alzheimer_metrics = evaluate_alzheimer()

    return brain_metrics, alzheimer_metrics


brain_metrics, alzheimer_metrics = load_metrics()

# -----------------------------------
# HEADER
# -----------------------------------

st.title(
    "Project Metrics"
)

st.info(
    """
Performance evaluation of both deep learning models used
in NeuroVision AI.
"""
)

st.markdown("---")

# -----------------------------------
# BRAIN TUMOR MODEL
# -----------------------------------

st.header(
    "Brain Tumor Detection Model"
)

col1, col2 = st.columns(2)

with col1:

    st.metric(
        "Accuracy",
        f"{brain_metrics['accuracy']:.2f}%"
    )

    st.metric(
        "Precision",
        f"{brain_metrics['precision']:.2f}%"
    )

with col2:

    st.metric(
        "Recall",
        f"{brain_metrics['recall']:.2f}%"
    )

    st.metric(
        "F1 Score",
        f"{brain_metrics['f1']:.2f}%"
    )

st.markdown("---")

# -----------------------------------
# ALZHEIMER MODEL
# -----------------------------------

st.header(
    "Alzheimer's Disease Detection Model"
)

col1, col2 = st.columns(2)

with col1:

    st.metric(
        "Accuracy",
        f"{alzheimer_metrics['accuracy']:.2f}%"
    )

    st.metric(
        "Precision",
        f"{alzheimer_metrics['precision']:.2f}%"
    )

with col2:

    st.metric(
        "Recall",
        f"{alzheimer_metrics['recall']:.2f}%"
    )

    st.metric(
        "F1 Score",
        f"{alzheimer_metrics['f1']:.2f}%"
    )

st.markdown("---")

# -----------------------------------
# MODEL INFORMATION
# -----------------------------------

st.header(
    "Model Information"
)

st.write("""
Architecture : ResNet18

Framework : PyTorch

Input Size : 224 × 224

Explainable AI : Grad-CAM

Frontend : Streamlit
""")

st.markdown("---")

# -----------------------------------
# DATASETS
# -----------------------------------

st.header(
    "Datasets Used"
)

with st.expander(
    "Brain Tumor Dataset",
    expanded=True
):

    st.write("""
• Glioma

• Meningioma

• Pituitary Tumor

• No Tumor
""")


with st.expander(
    "Alzheimer Dataset",
    expanded=True
):

    st.write("""
• Non Demented

• Very Mild Demented

• Mild Demented

• Moderate Demented
""")

st.markdown("---")

# -----------------------------------
# HEATMAP LEGEND
# -----------------------------------

st.header(
    "Heatmap Interpretation"
)

st.markdown("""
🔴 Red → Very High Attention

🟡 Yellow → High Attention

🟢 Green → Moderate Attention

🔵 Blue → Low Attention
""")

st.markdown("---")

# -----------------------------------
# DISCLAIMER
# -----------------------------------

st.warning(
    """
This application is intended for academic purposes only.

Predictions generated by these models should not
be considered a clinical diagnosis.

Please consult qualified healthcare professionals.
"""
)

st.markdown("---")

# -----------------------------------
# FOOTER
# -----------------------------------

st.caption(
    "NeuroVision AI | MRI-Based Brain Disease Detection using Deep Learning and Explainable AI"
)

# -----------------------------------
# BACK BUTTON
# -----------------------------------

if st.button(
    "Back To Model Selection",
    use_container_width=True
):
    st.switch_page(
        "pages/1_Model_Selection.py"
    )
